# Generated by Django 4.2.5 on 2023-10-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw2app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='img',
            field=models.ImageField(default=None, height_field=1000, upload_to='media', width_field=1000),
        ),
    ]
