# Generated by Django 4.2.5 on 2023-09-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminarapp2', '0002_author_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eagle', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
