# Generated by Django 4.2.5 on 2023-09-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminarapp2', '0003_coin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('biography', models.CharField(max_length=1000)),
                ('dob', models.DateField()),
            ],
        ),
    ]
